apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-operator-controller-manager
  namespace: fintech-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-09-02"
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 65532
      serviceAccountName: fintech-operator-controller-manager
      containers:
      - name: manager
        image: example.com/fintech-operator:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        command:
        - /manager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-operator-controller-manager
  namespace: fintech-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fintech-operator-role
rules:
- apiGroups:
  - fintech.io
  resources:
  - settlementworkers
  - tradingbots
  - reconciliationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fintech.io
  resources:
  - settlementworkers/finalizers
  - tradingbots/finalizers
  - reconciliationjobs/finalizers
  verbs:
  - update
- apiGroups:
  - fintech.io
  resources:
  - settlementworkers/status
  - tradingbots/status
  - reconciliationjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fintech-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fintech-operator-role
subjects:
- kind: ServiceAccount
  name: fintech-operator-controller-manager
  namespace: fintech-operator-system
