apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-operator-controller-manager
  namespace: fintech-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-09-02"
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 65532
      serviceAccountName: fintech-operator-controller-manager
      containers:
      - name: manager
        image: example.com/fintech-operator:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        - --metrics-bind-address=:8443
        command:
        - /manager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-operator-controller-manager
  namespace: fintech-operator-system
