---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fintech.fintech.io
  resources:
  - reconciliationjobs
  - settlementworkers
  - tradingbots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fintech.fintech.io
  resources:
  - reconciliationjobs/finalizers
  - settlementworkers/finalizers
  - tradingbots/finalizers
  verbs:
  - update
- apiGroups:
  - fintech.fintech.io
  resources:
  - reconciliationjobs/status
  - settlementworkers/status
  - tradingbots/status
  verbs:
  - get
  - patch
  - update
